### ISSUE TITLE
add a visual feedback if victory

### ISSUE THREAD

**Issue by spineki** [spineki/picklebreak#14]
We need to provide a visual feedback to celebrate victory
The following link explain how to make them.

showinfo(titre, message, option=valeur, ...) seems to be pretty good ^^

http://tkinter.fdex.eu/doc/popdial.html

**Comment by spineki** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [window.py](https://trello.com/c/WYToC6WD/16-windowpy)

**Comment by alex-lb33** [comment]
Done
