### ISSUE TITLE
Documentation and Code Structure

### ISSUE THREAD

**Issue by romainpascual** [spineki/picklebreak#7]
Add tests and documentation to `level_loader.py`.
If you choose to do Object Oriented Programming, please do so everywhere and no for half for the project.

**Comment by mrlag31** [comment]
A better code structure is in the making. However, it has not been merged yet.

**Comment by Remon-prog** [comment]
New script level_manager has been made to replace level_loader, it has documentation and uses classes

**Comment by spineki** [comment]
level_loader commented
